build:
  version: "3.0"

accounts:
  message: "Welcome to SBIBank account related local APIs"
  contact-details:
    name: "Subhash Patil - Developer"
    email: "subhash.patil@sbibank.com"
  on-call-support:
    - "(555) 555-1234"
    - "(555) 523-1234"