build:
  version : "1.0"

accounts:
  message: "Welcome to SBIBank account related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product owner"
    email: "aishwarya@sbibank.com"
  onCallSupport:
    - "(453) 392-4829"
    - "(523) 203-0384"

