build:
  version: "3.0"

loans:
  message: "Welcome to SBIBank loans related local APIs"
  contact-details:
    name: "Ajay Patil - Developer"
    email: "ajay.patil@sbibank.com"
  on-call-support:
    - "(452) 456-2176"
    - "(546) 764-8934"