spring:
  application:
    name: "configserver"
  profiles:
    active: native
    # active: git
  cloud:
    config:
      server:
        native:
          search-location: "classpath:/config"
server:
  port: 8071


