#server.port=8080

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.droverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.database-platform=org.hibernate.dialect.H2Dialect
#spring.console.enabled=update
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


build:
  version : "3.0"

accounts:
  message: "Welcome to SBIBank account related local APIs "
  contactDetails:
    name: "Subhash Patil - Developer"
    email: "subhash.patil@sbibank.com"
  onCallSupport:
    - "(555) 555-1234"
    - "(555) 523-1234"

